### PR TITLE
Populate tt.extern_elementwise conversion with trigonometric and hyperbolic functions

### PR DESCRIPTION
**Pull request by aobolensk**
Populate conversion pattern implementations with recently added functions to MLIR math dialect
- inverse trigonometric functions (asin, acos, atan)
- hyperbolic functions (sinh, cosh, tanh)
- inverse hyperbolic functions (asinh, acosh, atanh)

### CODE REVIEW

**Review by nhat-nguyen — APPROVED** [review]
LGTM! Let's merge this in and once this lands we can update all the lit tests at once to remove `libdevice`

**Comment by aobolensk** [comment]
> LGTM! Let's merge this in and once this lands we can update all the lit tests at once to remove `libdevice`

OK

**Comment by nhat-nguyen** [comment]
@aobolensk Just need you to update with latest main and we're good to go.

**Comment by aobolensk** [comment]
> @aobolensk Just need you to update with latest main and we're good to go.

Done

**Pull request merged**
