### PR TITLE
reworking arm workflow runner

### PR DESCRIPTION
**Pull request by danikhan632**

### CODE REVIEW

**Comment by nhat-nguyen** [comment]
@danikhan632 Just wanted to double check if you meant to merge this into @NathanielMcVicar's branch and not main? We might want to update his branch so that the diffs don't look too unwieldy 😄

**Comment by danikhan632** [comment]
yea, made that mistake, also is it a no-go to merge with my custom llvm binaries?
currently working on editing triton workflow runner to cross compile

**Comment by nhat-nguyen** [comment]
I can definitely accommodate adding the custom llvm binaries if it's just temporary for now. Can you update the target branch so it's easier to review?

**Comment by danikhan632** [comment]
Will do today, also merged PR upstream to fix arm64 builds

**Pull request closed without merging**
