### PR TITLE
Remove library name check for __nv_* intrinsics

### PR DESCRIPTION
**Pull request by aobolensk**
Triton does not set libdevice name for __nv_* intrinsics after https://github.com/openai/triton/pull/2887

- Remove check for libdevice for __nv_* intrinsics
- Remove particular NVIDIA-related libdevice name from the tests

### CODE REVIEW

**Comment by nhat-nguyen** [comment]
Thank you! Should we also update the tests to reflect this?

**Comment by aobolensk** [comment]
> Thank you! Should we also update the tests to reflect this?

We have released the limitation here, so library name is not checked, so there is no need to update. But to preserve consistency with what Triton actually emits as of now (could be changed in the future as well), it could be done. WDYT, is it needed?

**Comment by nhat-nguyen** [comment]
Yea I think let's keep the tests consistent with what triton emits, it will be easier to keep track in the future.

**Comment by aobolensk** [comment]
> Yea I think let's keep the tests consistent with what triton emits, it will be easier to keep track in the future.

OK, I'll update after #98 is merged

**Comment by aobolensk** [comment]
Done

**Review by nhat-nguyen — APPROVED** [review]

**Pull request merged**
