### PR TITLE
Test ARM 1ES pool

### PR DESCRIPTION
**Pull request by NathanielMcVicar**
This tests the ARM 1ES pool, once the pool is working #66 can move forward and the workflow temporarily created here can be deleted.

### CODE REVIEW

**Comment by danikhan632** [comment]
> This tests the ARM 1ES pool, once the pool is working #66 can move forward and the workflow temporarily created here can be deleted.

Should be able to close my PR and move it to here now that workflow runner is setup, the only concern I have is from #72 since triton made some update that breaks this repo and that predates my PR that added the support to the setup.py to enable arm64. If we have to use a build of triton that predates my ![triton PR] (https://github.com/openai/triton/commit/801bb5fb4dc263a66b1c6e08a8b179807eb4028a) then we will still have to transplant a newer setup.py as shown in my PR in order to run the workflow. Also the triton repo has not re-run the llvm build workflow so arm llvm doesn't exist yet. But hopefully this will be dealt with and #66 can be closed out

**Comment by NathanielMcVicar** [comment]
@danikhan632 
> Should be able to close my PR and move it to here
My intent was that you would close this PR once you confirmed yours was working with the Pool, since this was just a test workflow and has nothing to do with the ARM pool itself, but I'll leave that up to you. Thanks again for adding support!

**Comment by danikhan632** [comment]
> @danikhan632
> 
> > Should be able to close my PR and move it to here
> 
> My intent was that you would close this PR once you confirmed yours was working with the Pool, since this was just a test workflow and has nothing to do with the ARM pool itself, but I'll leave that up to you. Thanks again for adding support!

Thanks for the clarification, looks like I'm going to have to keep testing the workflow with the arm pool since it failed😭, still trying to figure out why that one test for the x64 failed but it doesn't look like the arm pool has pip installed for python3, could that be changed by running
```bash
sudo apt-get -y install python3-pip      
```

or should I install pip as part of the workflow?

**Comment by NathanielMcVicar** [comment]
Unfortunately, I can't find a complete list of installed software for the ARM image. For the GitHub hosted runners you can find it here: https://github.com/actions/runner-images#software-and-image-support. It's not ideal, but I think you will just have to continue with your current trial and error process to get the software you need installed.

**Comment by danikhan632** [comment]
> Unfortunately, I can't find a complete list of installed software for the ARM image. For the GitHub hosted runners you can find it here: https://github.com/actions/runner-images#software-and-image-support. It's not ideal, but I think you will just have to continue with your current trial and error process to get the software you need installed.

sounds good, wanted to know if its possible if I could manually trgger workflows. Not being able to manually do so does make trial and error a bit harder

**Comment by NathanielMcVicar** [comment]
> sounds good, wanted to know if its possible if I could manually trgger workflows. Not being able to manually do so does make trial and error a bit harder

Oh, I see what you mean. You need to add an `on: workflow_dispatch:` trigger to integration-tests.yml. You can look at nightly-tests.yml for an example. Then you should be able to trigger it manually against your branch.

**Comment by nhat-nguyen** [comment]
Closing since #103 has now been merged.

**Pull request closed without merging**
