### PR TITLE
Update triton to 310405647df51a909943bed71c5a6fd9a3e402b4

### LINKED ISSUE #169: Nightly Build Failure 2024-08-23
cc @microsoft/aifx-compilers
              The nightly build has failed. See: https://github.com/microsoft/triton-shared/actions/runs/10524204455

### PR DESCRIPTION
**Pull request by nhat-nguyen**
+ Install pybind11 during setup
+ Implement `get_module_map`
+ Fix missing argument materialization hook in StructuredToMemref
+ Update signatures in UseAnalysis

Fixes #169

### CODE REVIEW

**Comment by nhat-nguyen** [comment]
@parsifal-47 I'm fixing the nightly build but the `test_core.py` now fails with the following error in `test_binary`. Just wondering if you have seen `Floating point exception` while bringing up these tests before? Thank you.

Error:

```
test_core.py ...........s............s...........s...........s.......... [  0%]
.s...........s...........s...........s...........s...........s.......... [  1%]
.s...........sssssssssssss...........s...........s...........s.......... [  1%]
.s...........s...........s...........s...........s...........s.......... [  2%]
.s...........sssssssssssss...........s...........s...........s.......... [  2%]
.s...........s...........s...........s...........s...........s.......... [  3%]
.s...........sssssssssssss...........s...........s...........s.......... [  4%]
.s...........s...........s...........s...........s...........s.......... [  4%]
Fatal Python error: Floating point exception

Current thread 0x00007fb24d8e4000 (most recent call first):
  File "/home/runner/.local/lib/python3.10/site-packages/triton/backends/triton_shared/driver.py", line 267 in launch
  File "/home/runner/.local/lib/python3.10/site-packages/triton/backends/triton_shared/driver.py", line 290 in __call__
  File "/home/runner/.local/lib/python3.10/site-packages/triton/runtime/jit.py", line 687 in run
  File "/home/runner/.local/lib/python3.10/site-packages/triton/runtime/jit.py", line 330 in <lambda>
  File "/home/runner/work/triton-shared/triton-shared/triton_shared/python/examples/test_core.py", line 347 in do_test
  File "/home/runner/work/triton-shared/triton-shared/triton_shared/python/examples/test_core.py", line 377 in _test_binary
  File "/home/runner/work/triton-shared/triton-shared/triton_shared/python/examples/test_core.py", line 465 in test_bin_op
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/python.py", line 159 in pytest_pyfunc_call
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/python.py", line 1627 in runtest
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/runner.py", line 174 in pytest_runtest_call
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/runner.py", line 242 in <lambda>
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/runner.py", line 341 in from_call
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/runner.py", line 241 in call_and_report
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/runner.py", line 132 in runtestprotocol
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/runner.py", line 113 in pytest_runtest_protocol
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/main.py", line 362 in pytest_runtestloop
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/main.py", line 337 in _main
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/main.py", line 283 in wrap_session
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/main.py", line 330 in pytest_cmdline_main
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/runner/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 175 in main
  File "/home/runner/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 201 in console_main
  File "/home/runner/.local/bin/pytest", line 8 in <module>

Extension modules: numpy._core._multiarray_umath, numpy.linalg._umath_linalg, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt[19](https://github.com/microsoft/triton-shared/actions/runs/10744594348/job/29801887358?pr=175#step:12:20)937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, __triton_shared_ref_cpu_kernel_launcher (total: 19)
/home/runner/work/_temp/a68a4714-c88f-4aa0-a827-19dd22543fa8.sh: line 1:  7272 Floating point exception(core dumped) pytest .```

**Comment by parsifal-47** [comment]
> Just wondering if you have seen Floating point exception while bringing up these tests before?

I haven't seen this error on main, it means something like division by zero in C++ extension code,
even when most of the tests were not passing, they still were runnable. I just fetched the branch and started the tests to see if I can get more insight from the core dump. I will follow-up.

**Comment by parsifal-47** [comment]
after updating, it got so much slower, I am still waiting for the build

**Comment by parsifal-47** [comment]
> @parsifal-47 I'm fixing the nightly build but the `test_core.py` now fails with the following error in `test_binary`. Just wondering if you have seen `Floating point exception` while bringing up these tests before? Thank you.

I have reproduced the crash, but haven't fixed it yet, let's skip this test for now and skip one more new case related to fp8, with the diff below it passes:

```
diff --git a/python/examples/conftest.py b/python/examples/conftest.py
index 77b4d46..293168a 100644
--- a/python/examples/conftest.py
+++ b/python/examples/conftest.py
@@ -19,6 +19,7 @@ def device(request):


 tests_not_supported = {
+    "test_bin_op",
     "test_split",
     "test_split_to_scalar",
     "test_interleave_scalars",
@@ -105,5 +106,5 @@ def pytest_collection_modifyitems(config, items):
                     item.add_marker(skip_marker_bfloat)
                 if param_name.startswith('input_precision') and param_value.startswith('tf32'):
                     item.add_marker(skip_marker_tf32)
-                if param_name.endswith('dtype') and ('float8' in str(param_value)):
+                if (param_name.startswith('dtype') or param_name.endswith('dtype')) and ('float8' in str(param_value)):
                     item.add_marker(skip_marker_float8)
```

**Comment by nhat-nguyen** [comment]
@parsifal-47 Thank you!

**Review by red1bluelost — APPROVED** [review]

**Pull request merged**
